In [60]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [61]:
df=pd.read_csv('Fish.csv')

In [62]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [63]:
df.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [65]:
df['Species'].value_counts()

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

In [66]:
X=df.drop("Weight",axis=1)
Y=df[['Weight']]

In [67]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression

In [68]:
print(X)

    Species  Length1  Length2  Length3   Height   Width
0     Bream     23.2     25.4     30.0  11.5200  4.0200
1     Bream     24.0     26.3     31.2  12.4800  4.3056
2     Bream     23.9     26.5     31.1  12.3778  4.6961
3     Bream     26.3     29.0     33.5  12.7300  4.4555
4     Bream     26.5     29.0     34.0  12.4440  5.1340
..      ...      ...      ...      ...      ...     ...
154   Smelt     11.5     12.2     13.4   2.0904  1.3936
155   Smelt     11.7     12.4     13.5   2.4300  1.2690
156   Smelt     12.1     13.0     13.8   2.2770  1.2558
157   Smelt     13.2     14.3     15.2   2.8728  2.0672
158   Smelt     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 6 columns]


In [69]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [70]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [71]:
print(X)

[[ 1.    0.    0.   ... 30.   11.52  4.02]
 [ 1.    0.    0.   ... 31.2  12.48  4.31]
 [ 1.    0.    0.   ... 31.1  12.38  4.7 ]
 ...
 [ 0.    0.    0.   ... 13.8   2.28  1.26]
 [ 0.    0.    0.   ... 15.2   2.87  2.07]
 [ 0.    0.    0.   ... 16.2   2.93  1.88]]


In [72]:
lr=LinearRegression()

In [73]:
lr.fit(X_train,Y_train)

LinearRegression()

In [74]:
y_train_pred=lr.predict(X_train)

In [75]:
y_test_pred=lr.predict(X_test)

In [76]:
Y_test.shape

(32, 1)

In [77]:
y_test_pred.shape

(32, 1)

In [78]:
df6=Y_test.copy()

In [79]:
df6['y_pred']=y_test_pred

In [80]:
df6

Weight       y_pred
29   1000.0   786.895932
42    120.0   106.877114
14    600.0   546.186655
91    130.0   193.616759
81     85.0    70.677603
19    650.0   604.768801
44    145.0   122.903964
11    500.0   487.351516
40      0.0    70.768553
97    145.0   242.687360
89    135.0   174.814756
94    150.0   215.594484
73     32.0  -185.242525
105   250.0   371.342788
59    800.0   711.881818
90    110.0   188.966132
66    140.0   183.488387
54    390.0   536.004961
108   320.0   467.590714
100   197.0   308.048929
153     9.8    -0.621707
35     40.0  -171.049562
51    180.0   249.667531
5     450.0   495.212598
84    125.0   147.155398
31    955.0   833.637984
16    700.0   584.900687
145     6.7   -83.455803
143  1550.0  1280.466730
93    145.0   199.423873
127  1000.0  1027.005160
103   260.0   366.930286

In [ ]:
plt.scatter(df6[])