# Data Preprocessing Tools

## Importing the libraries

In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [84]:
dataset=pd.read_csv("Data.csv")
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

In [85]:
print(X)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [86]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [87]:
from sklearn.impute import SimpleImputer
Imputer=SimpleImputer(missing_values=np.nan, strategy='median')
Imputer.fit(X[:, 1:3])
X[:, 1:3]=Imputer.transform(X[:, 1:3])


simpleImputer used to handle missing data

In [88]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [89]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [90]:
print(X)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [91]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
Y = label.fit_transform(Y)

In [92]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [93]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [94]:
print(X_train)

[[0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [95]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [96]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [97]:
print(y_test)

[0 1]


## Feature Scaling

In [98]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.fit_transform(X_test[:,3:])

In [99]:
print(X_train)

[[0.0 0.0 1.0 -0.28942984211696865 -1.0430254692900243]
 [0.0 1.0 0.0 0.0 -0.2767210428728636]
 [1.0 0.0 0.0 0.5788596842339373 0.659873256081444]
 [0.0 0.0 1.0 -0.28942984211696865 -0.2767210428728636]
 [0.0 0.0 1.0 -1.8812939737602963 -1.383605214364318]
 [1.0 0.0 0.0 1.1577193684678746 1.2558878099614579]
 [0.0 1.0 0.0 1.4471492105848434 1.5964675550357514]
 [1.0 0.0 0.0 -0.7235746052924217 -0.5321558516785838]]


In [100]:
print(X_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
